### ISSUE TITLE
962915 - The Parish School (50C9C98A3D21E02F)

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#1]
Jennifer Beleiff will be the administrator
Admin: jbeleiff@parishschool.org
Order: 962915
MasterCode: 50C9C98A3D21E02F
Spreadsheet: https://www.dropbox.com/s/8w0zin5veye7l4u/962915_TheParishSchool.csv?dl=0

**Comment by nishp1** [comment]
Needs CSV.

**Comment by nishp1** [comment]
Done!
