### ISSUE TITLE
958819 - kstrauman@illinicentral.org ( D0EE3F0322D59A34 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#11]
Kaitlyn Strauman will be the administrator
admin : kstrauman@illinicentral.org
orderNbr : 958819
masterCode : D0EE3F0322D59A34
spreadsheet : https://www.dropbox.com/s/ce70y2iz0qr50d6/958819_Illincentral%20Grade%20School.csv?dl=0

**Comment by nishp1** [comment]
Bad order?
```
{
    "message": "Success!",
    "availableLicenses": {
        "KEYK": 0,
        "KEY1": 0,
        "KEY2": 0,
        "KEY3": 0,
        "KEY4": 0,
        "KEY5": 300
    },
    "requiredLicenses": {
        "KEYK": 52,
        "KEY1": 45,
        "KEY2": 48,
        "KEY3": 45,
        "KEY4": 57,
        "KEY5": 49
    }
}
```

**Comment by crooner** [comment]
Took the liberty of properly distributing these licenses, since the customer can't figure out what to order. All set.
