### ISSUE TITLE
956236 - tbargo@alvaschools.net ( B22081E9939C62F8 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#12]
Tim Argo will be the administrator
admin : tbargo@alvaschools.net
orderNbr 956236
masterCode : B22081E9939C62F8
spreadsheet : https://www.dropbox.com/s/9ixb2w4ayapqbib/956236_LincolnES.csv?dl=0

**Comment by nishp1** [comment]
Done!
