### ISSUE TITLE
961345 - awaldman@ebrooke.org ( 00B0EB5DE86DD7EA )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#13]
Abigail Waldman will be the administrator
admin :  awaldman@ebrooke.org
orderNbr : 961345
masterCode : 00B0EB5DE86DD7EA
spreadsheet : https://www.dropbox.com/s/4pe6mc7rt4b1usm/957348_BrookeCharterSchools.csv?dl=0

**Comment by nishp1** [comment]
Done! Had to swap 23 KEY5 to KEY4.
