### ISSUE TITLE
954962 - donna.warner@wbrschools.net ( 02DBCB312608AE57 ) 

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#14]
Donna Warner will be the administrator.
admin : donna.warner@wbrschools.net
orderNbr : 954962
masterCode : 02DBCB312608AE57
spreadsheet :  https://www.dropbox.com/s/1613bw0n1sx0ggw/954962_WestonBatonRouge_partial.csv?dl=0

Note: This spreadsheet contains Kindergarten and 1st graders, although their are other liceses in this order. The rest of the classes to come later. Please process these now though.

**Comment by nishp1** [comment]
Looks like they created classes and students, but not assigned licenses. Additionally, CSV has all names uppercased.

**Comment by crooner** [comment]
If no progress data,  wipe them out and go with the bulk import spreadsheet. Play close attention to any progress data to make sure it is for these students (not other ones with other licenses).

**Comment by nishp1** [comment]
What about upper cased names? Is that how they want it?

**Comment by crooner** [comment]
Fixed the upper cased names with Excel =proper(C2) function.
