### ISSUE TITLE
955936 - across@kippstriveprimary.org ( B02E21DA4BA0E412 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#17]
Ali Cross will be the administrator,
admin : across@kippstriveprimary.org
orderNbr : 955936
masterCode : B02E21DA4BA0E412
spreadsheet : https://www.dropbox.com/s/btugcy2l9gg8m7l/308630_KIPP_GCP_primary.csv?dl=0

Not sure if you've processed this one of not, but I want to keep a record for each. If you have processed this one, could you close this issue and maybe move the CSV from the Unprocessed folder to the Processed folder in DropBox?

**Comment by nishp1** [comment]
Link is incorrect based on order nbr. It should be 955936_KippStriveES.csv

**Comment by nishp1** [comment]
Processed 955936_KippStriveES.csv
