### ISSUE TITLE
948891- kmiklos@wearesynergy.org ( FD6A3A6136224DEA )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#18]
Kristin Miklos will be the administrator,
admin : kmiklos@wearesynergy.org
orderNbr : 948891
masterCode : FD6A3A6136224DEA
spreadsheet : https://www.dropbox.com/s/wt81bpx3pee5hjv/948891_SynergyCharter.csv?dl=0

Not sure if this one has been done or not yet.

**Comment by nishp1** [comment]
Looks done!
