### ISSUE TITLE
961151 - Kathryn Senor ES  (94A598169F3AFB17)

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#2]
Julie Robbins will be the administrator
admin: jrobbins@garfieldre2.org
orderNbr: 961151
masterCode: 94A598169F3AFB17
spreadSheet: https://www.dropbox.com/s/9hcwxhvy38n0vkb/961151%20-%20Kathryn%20Senor%20Elementary.csv?dl=0

**Comment by nishp1** [comment]
Processed!
