### ISSUE TITLE
874913 - jfriend@windberschools.org ( 93D60C15E4E5D376 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#22]
Jeff Friend will be the administrator.
admin : jfriend@windberschools.org
orderNbr : 874913
masterCode :  93D60C15E4E5D376
spreadsheet : https://www.dropbox.com/s/umail04qjpgrmwu/874913_WindbergAreaSD.csv?dl=0

**Comment by nishp1** [comment]
Done!
