### ISSUE TITLE
956531 - pkrason@braemarhouseschool.ca ( D2038D1D78C87E87 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#23]
Pam Krason will be the administrator 
admin: pkrason@braemarhouseschool.ca
orderNbr : 956531. 
masterCode : D2038D1D78C87E87
spreadsheet : https://www.dropbox.com/s/yy11329nixauk92/956531_BraemerHouseSchool.csv?dl=0

**Comment by nishp1** [comment]
Done!
