### ISSUE TITLE
945641- admin@nashvillesd.com ( FE8FC4702C5CEB5F )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#27]
Bryce Petty will be the administrator
admin : admin@nashvillesd.com
orderNbr : 945641
masterCode : FE8FC4702C5CEB5F
spreadsheet : https://www.dropbox.com/s/1el1lafyzz0jdor/945641_NashvillePrimary.csv?dl=0

**Comment by crooner** [comment]
Header too long.

**Comment by crooner** [comment]
This bulk import shows that is succeeded, but it does not create classes, teachers, etc. Nish, could you please take a look at this one and try it again. 

![image](https://cloud.githubusercontent.com/assets/3969469/9386523/d8cd43b4-4729-11e5-90fb-418c3ae81ca7.png)

**Comment by nishp1** [comment]
Class Name column was Class.
