### ISSUE TITLE
957388 and 955914 - The Worth Schools (8E106782A817B755 and 88C5F07B1330F50D)

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#3]
Christy Haskins will be the administrator 
Admin: chaskins@worthschools.net
Order : 957388 and 955914
MasterCode : 8E106782A817B755 and 88C5F07B1330F50D
spreadSheet: https://www.dropbox.com/s/hz25w57bkycqxk3/957388_955914_WorthSchools.csv?dl=0

**Comment by nishp1** [comment]
Master code belongs to achafin@worthschools.net. Does that need be changed?

**Comment by nishp1** [comment]
Done! Had to take 20 KEYK and transfer some over to KEY3,KEY4, and KEY5.
