### ISSUE TITLE
962673 - jwhite2@nccsc.k12.in.us  (096B842DCD8D8DD2)

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#4]
Jacob White will be the administrator
admin: jwhite2@nccsc.k12.in.us
order : 962673
masterCode : 096B842DCD8D8DD2
spreadSheet: https://www.dropbox.com/s/lfueglor30ocdys/962673_NewCastleCommunitySchool.csv?dl=0

**Comment by nishp1** [comment]
Done!

Had 6th grade students and licenses, had to change to KEY5.
