### ISSUE TITLE
957348 -  rjohnson@ebrooke.org ( B7C1464F508D8EE8 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#5]
Rachel Johnson will be the administrator 
admin: rjohnson@ebrooke.org
orderNbr : 957348
masterCode : B7C1464F508D8EE8
spreadsheet: https://www.dropbox.com/s/4pe6mc7rt4b1usm/957348_BrookeCharterSchools.csv?dl=0

**Comment by nishp1** [comment]
Done! Added 1 KEY3 license.
