### ISSUE TITLE
958954 - sbulleri@fbcstockton.org ( 3E6BA13104CBBCEA )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#6]
Stephanie Bulleri will be the administrator
admin: sbulleri@fbcstockton.org
orderNbr : 958954
master code : 3E6BA13104CBBCEA
spreadsheet: https://www.dropbox.com/s/ne8xdexmwq612xq/958954_FirstBaptistChristianSchool.csv?dl=0

Note: This one has some allocated, but no activities when I checked.

**Comment by nishp1** [comment]
Seems done.
