### ISSUE TITLE
954962 - donna.warner@wbrschools.net ( 02DBCB312608AE57 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#7]
Donna Warner will be the administrator
admin: donna.warner@wbrschools.net
order : 954962
masterCode : 02DBCB312608AE57
spreadsheet : https://www.dropbox.com/s/hj6rlp2hv4xjz08/954962_WestonBatonRougeParishSchoolBoard.csv?dl=0

**Comment by nishp1** [comment]
They already have created classes and students but not assigned licenses. And CSV has all names upper cased.

**Comment by nishp1** [comment]
Done!
