### ISSUE TITLE
965220 - jpasteur@ntxleadershipacademy.org ( 27A4E2C8254CF0BF )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#8]
Jennifer Pasteur will be the administrator
Admin : jpasteur@ntxleadershipacademy.org
orderNbr : 965220
masterCode : 27A4E2C8254CF0BF
spreadsheet : https://www.dropbox.com/s/5wy9i2bzabb5vue/965220_NorthTexasLeadershipAcademy.csv?dl=0

**Comment by nishp1** [comment]
Done!
