### ISSUE TITLE
950631 -  johnny.haley@academicsplus.org ( F48EFF754D290927 )

### ISSUE THREAD

**Issue by crooner** [crooner/bulkImports#9]
Johnny Haley will be the administrator
Admin :  johnny.haley@academicsplus.org
orderNbr : 950631
masterCode : F48EFF754D290927
spreadsheet : https://www.dropbox.com/s/tg0tbvo9hx6f22f/950631_AcademicsPlusCS.csv?dl=0

**Comment by nishp1** [comment]
```json
{
    "error": "Not enough licenses to allocate for KEY1. Requested: 94, Available: 85",
    "availableLicenses": {
        "KEYK": 110,
        "KEY1": 85,
        "KEY2": 75,
        "KEY3": 75
    },
    "requiredLicenses": {
        "KEYK": 98,
        "KEY1": 94,
        "KEY2": 72,
        "KEY3": 72
    }
}
```

**Comment by nishp1** [comment]
Should I transfer 11 KEYK to KEY1?

**Comment by crooner** [comment]
Yup.

**Comment by nishp1** [comment]
Grr...looks like admin had an account "notears@academicsplus.org" last year under which all users are registered. Only options is to transfer the license to "notears@academicsplus.org", since we can't have multiple admins.

**Comment by nishp1** [comment]
Errors after another....one user has academcisplus (wrong), instead of academicsplus (right).

**Comment by crooner** [comment]
I removed the bad username from the database. Looks like you may have partially run this, because the correct username is in the database, the MasterCode is unlocked and the licenses allocated to the correct admin, but none of the classes or students are setup. 

I started to run the import, but realized that since I haven't done any new (2.0) imports, I am astill pointing to hq-bennett for the web service call. Where should I be pointing?

**Comment by crooner** [comment]
Done
